#!/usr/bin/env bash
# build-spec-sheet.sh — generate the component catalog (spec-sheet.html)
# usage: scripts/build-spec-sheet.sh [kit.css] [out.html]
# spec-sheet.html is GENERATED — never hand-edit; rerun this script.
# Kit swap (e.g. carbon.css) = pass another kit file; fragments are
# token-driven so the same sheet reskins with zero fragment changes.
set -euo pipefail

KIT="${1:-references/foundations/geist.css}"
OUT="${2:-references/components/spec-sheet.html}"
COMP="references/components"

if [ ! -f "$KIT" ]; then echo "FAIL: kit not found: $KIT"; exit 1; fi
if [ ! -f "$COMP/_base.css" ]; then echo "FAIL: $COMP/_base.css not found"; exit 1; fi

FRAGS=(cover hero-metric kpi-tiles badges source-line margin-note section-head
       callout-highlight callout-side data-table chart-bar chart-line chart-stacked
       diagram code-block)

for f in "${FRAGS[@]}"; do
  if [ ! -f "$COMP/$f.html" ]; then echo "FAIL: fragment missing: $COMP/$f.html"; exit 1; fi
done

{
cat <<'HEAD'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>report-builder — component spec sheet (GENERATED)</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700;800&family=Geist+Mono:wght@400;500;600&family=Source+Serif+4:ital,opsz,wght@1,8..60,400;0,8..60,600&display=swap');
HEAD
cat "$KIT"
cat "$COMP/_base.css"
cat <<'SCAFFOLD'
/* demo scaffolding (spec-sheet only — not part of any fragment) */
.wrap{max-width:1180px;margin:0 auto;padding:72px 32px}
.mast{padding-bottom:24px;border-bottom:2px solid var(--ink)}
.mast .k{font-family:var(--mono);font-size:var(--t-eye);text-transform:uppercase;letter-spacing:.10em;color:var(--ink-mute)}
.mast h1{font-size:var(--t-dlg);font-weight:700;letter-spacing:-.025em;margin-top:8px}
.mast p{color:var(--ink-soft);font-size:var(--t-sm);margin-top:8px}
.frag{margin-top:48px}
.frag-label{font-family:var(--mono);font-size:11px;color:var(--ink-mute);text-transform:uppercase;letter-spacing:.06em;
  margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--hairline-2)}
</style>
</head>
<body>
<div class="wrap">
<div class="mast">
  <div class="k">hukuhaka-report-builder · references/components</div>
  <h1>Component spec sheet</h1>
  <p>GENERATED by scripts/build-spec-sheet.sh — never hand-edit. Kit: KIT_NAME. Each block below is the verbatim fragment file.</p>
</div>
SCAFFOLD
for f in "${FRAGS[@]}"; do
  printf '<div class="frag"><div class="frag-label">%s.html</div>\n' "$f"
  cat "$COMP/$f.html"
  printf '</div>\n'
done
cat <<'FOOT'
</div>
</body>
</html>
FOOT
} > "$OUT"

KITBASE="$(basename "$KIT")"
sed -i '' "s|KIT_NAME|$KITBASE|" "$OUT" 2>/dev/null || sed -i "s|KIT_NAME|$KITBASE|" "$OUT"

echo "OK: wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes, ${#FRAGS[@]} fragments, kit: $KITBASE)"
